name: "Scrape & Update JSON"
on:
  workflow_dispatch:
  schedule:
    - cron: "*/45 * * * *"
  # optional: comment out 'push' to avoid collisions
  # push:
  #   branches: [ main ]

permissions:
  contents: write
concurrency:
  group: scrape-json
  cancel-in-progress: true

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      # Pull BEFORE generating files (clean tree)
      - name: Sync with origin
        run: |
          git fetch origin main
          git -c rebase.autoStash=true pull --rebase origin main

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i
      - run: node scripts/scrape.mjs

      - name: Commit JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/data/*.json
          git commit -m "data: update $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push origin HEAD:main
